# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'dayy24' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dayy24
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
end
