# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'day 24' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for day 24
# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'


end
